In [1]:
# Importamos bibliotecas.
import numpy as np
import pandas as pd

In [2]:
# Abrimos el dataframe.
datasets_path = '../datasets/customer-churn-model/'
file_name = 'Customer Churn Model.txt'
file_path = datasets_path + file_name

# Abrimos en modo de lectura, 'r'.
file = open(file_path, 'r')

In [3]:
# Con 'readline' leemos la primer línea, con 'strip' eliminamos espacios en blanco, y con 'split' dividimos por comas.
cols = file.readline().strip().split(',')
print(cols)

['State', 'Account Length', 'Area Code', 'Phone', "Int'l Plan", 'VMail Plan', 'VMail Message', 'Day Mins', 'Day Calls', 'Day Charge', 'Eve Mins', 'Eve Calls', 'Eve Charge', 'Night Mins', 'Night Calls', 'Night Charge', 'Intl Mins', 'Intl Calls', 'Intl Charge', 'CustServ Calls', 'Churn?']

In [4]:
# Podemos crear un diccionario 'dd' (data dictionary) que sea equivalente a un dataframe de pandas con lo siguiente.
dd = {}
for col in cols:
    dd[col] = []

# Definimos un contador de filas y uno de columnas.
num_lines = 0
num_cols = len(cols)

# Lo rellenamos barriendo el archivo.
for line in file:
    values = line.strip().split(',')
    for i in range(num_cols):
        dd[cols[i]].append(values[i])
    num_lines += 1

print(f'Tenemos {num_cols} columnas, y {num_lines} filas')

# Cerramos el archivo que abrimos.
file.close()

Tenemos 21 columnas, y 3333 filas

In [5]:
# Con pandas podemos crear un dataframe con este diccionario.
df = pd.DataFrame(dd)
df.head()

,State,Account Length,Area Code,Phone,Int'l Plan,VMail Plan,VMail Message,Day Mins,Day Calls,Day Charge,...,Eve Calls,Eve Charge,Night Mins,Night Calls,Night Charge,Intl Mins,Intl Calls,Intl Charge,CustServ Calls,Churn?
0,KS,128,415,382-4657,no,yes,25,265.100000,110,45.070000,...,99,16.780000,244.700000,91,11.010000,10.000000,3,2.700000,1,False.
1,OH,107,415,371-7191,no,yes,26,161.600000,123,27.470000,...,103,16.620000,254.400000,103,11.450000,13.700000,3,3.700000,1,False.
2,NJ,137,415,358-1921,no,no,0,243.400000,114,41.380000,...,110,10.300000,162.600000,104,7.320000,12.200000,5,3.290000,0,False.
3,OH,84,408,375-9999,yes,no,0,299.400000,71,50.900000,...,88,5.260000,196.900000,89,8.860000,6.600000,7,1.780000,2,False.
4,OK,75,415,330-6626,yes,no,0,166.700000,113,28.340000,...,122,12.610000,186.900000,121,8.410000,10.100000,3,2.730000,3,False.